### Elevation trend analysis based on altimeter data.

In [19]:
import matplotlib.pyplot as plt
import numpy as np
import h5py

In [20]:
### 1. elevation difference statistics of each year.
path_sta_isat_2003 = 'data/icesat-1/GLAH14-2003/tiles/static_dif.h5'
path_sta_isat_2004 = 'data/icesat-1/GLAH14-2004/tiles/static_dif.h5'
path_sta_isat_2005 = 'data/icesat-1/GLAH14-2005/tiles/static_dif.h5'
path_sta_isat_2006 = 'data/icesat-1/GLAH14-2006/tiles/static_dif.h5'
path_sta_isat_2007 = 'data/icesat-1/GLAH14-2007/tiles/static_dif.h5'
path_sta_isat_2008 = 'data/icesat-1/GLAH14-2008/tiles/static_dif.h5'
path_sta_isat_2009 = 'data/icesat-1/GLAH14-2009/tiles/static_dif.h5'

In [21]:
!h5ls $path_sta_isat_2003

mean_glacier             Dataset {28}
mean_stable              Dataset {28}
num_glacier              Dataset {28}
num_stable               Dataset {28}
std_glacier              Dataset {28}
std_stable               Dataset {28}
tile                     Dataset {28}

In [22]:
import pandas as pd
sta_isat_2003 = h5py.File(path_sta_isat_2003, 'r')
sta_isat_2004 = h5py.File(path_sta_isat_2004, 'r')
sta_isat_2005 = h5py.File(path_sta_isat_2005, 'r')
sta_isat_2006 = h5py.File(path_sta_isat_2003, 'r')
sta_isat_2007 = h5py.File(path_sta_isat_2003, 'r')
sta_isat_2008 = h5py.File(path_sta_isat_2003, 'r')
sta_isat_2009 = h5py.File(path_sta_isat_2003, 'r')
sta_isat_2003

In [23]:
sta_2003_df = {}
for key in sta_isat_2003.keys():
    sta_2003_df[key]=sta_isat_2003[key][:]
sta_2003_df = pd.DataFrame(sta_2003_df)

mean_glacier
mean_stable
num_glacier
num_stable
std_glacier
std_stable
tile

In [25]:
sta_2003_df

,mean_glacier,mean_stable,num_glacier,num_stable,std_glacier,std_stable,tile
0,NaN,-0.946289,0,515,NaN,4.476455,b'tile_31_91'
1,NaN,-0.654053,0,884,NaN,3.708275,b'tile_31_92'
2,10.957031,-0.499512,2,214,2.026855,9.242875,b'tile_31_93'
3,NaN,1.962402,0,27,NaN,30.692736,b'tile_31_94'
4,NaN,-1.219971,0,117,NaN,17.015131,b'tile_31_95'
5,NaN,-1.514404,0,194,NaN,14.852345,b'tile_30_91'
6,NaN,-1.446289,0,115,NaN,4.675091,b'tile_30_92'
7,0.252197,1.625488,20,69,30.404848,34.283745,b'tile_30_93'
8,-4.669922,-0.235840,1,87,0.000000,37.681732,b'tile_30_94'
9,-3.409424,2.356934,4,38,10.849151,34.954422,b'tile_30_95'
10,NaN,-2.058594,0,231,NaN,18.397926,b'tile_30_96'
11,NaN,-0.537109,0,143,NaN,13.713204,b'tile_30_97'
12,NaN,-1.874756,0,349,NaN,9.016983,b'tile_29_91'
13,NaN,-1.059326,0,44,NaN,9.618898,b'tile_29_92'
14,NaN,-1.138306,0,110,NaN,20.561476,b'tile_29_93'
15,NaN,-2.878662,0,69,NaN,22.197802,b'tile_29_94'
16,13.863525,-2.385986,2,19,2.396729,38.520618,b'tile_29_95'
17,1.442139,-1.345947,6,93,14.424396,11.589420,b'tile_29_96'
18,14.162598,-1.185547,2,140,12.342773,23.933041,b'tile_29_97'
19,NaN,3.007324,0,19,NaN,35.434784,b'tile_29_98'
20,NaN,-2.218933,0,21,NaN,24.628054,b'tile_28_94'
21,NaN,0.632355,0,59,NaN,2.711338,b'tile_28_95'
22,NaN,0.168945,0,28,NaN,26.158806,b'tile_28_96'
23,-24.175781,-0.589844,4,115,15.037437,37.042503,b'tile_28_97'
24,NaN,-1.630737,0,16,NaN,39.566677,b'tile_28_98'
25,NaN,1.566727,0,15,NaN,4.614883,b'tile_27_96'
26,NaN,-2.878601,0,176,NaN,12.722993,b'tile_27_97'
27,NaN,-12.646484,0,2,NaN,0.349365,b'tile_27_98'